"""first revision

Revision ID: 04672a79dbf0
Revises: 
Create Date: 2022-08-02 11:04:41.066074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04672a79dbf0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shortned',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('short_url', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shortned_short_url'), 'shortned', ['short_url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shortned_short_url'), table_name='shortned')
    op.drop_table('shortned')
    # ### end Alembic commands ###
