"""async first revision

Revision ID: 706f57e034ce
Revises: 
Create Date: 2022-08-02 12:05:35.984906

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '706f57e034ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('async_test',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('original_url', sa.String(length=255), nullable=True),
    sa.Column('short_url', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_url')
    )
    op.drop_table('shorturl')
    op.drop_index('short_url', table_name='shortned')
    op.drop_table('shortned')
    op.drop_table('testa')
    op.drop_index('short_url', table_name='test')
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('original_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('short_url', mysql.VARCHAR(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('short_url', 'test', ['short_url'], unique=False)
    op.create_table('testa',
    sa.Column('id', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('original_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('short_url', mysql.VARCHAR(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('shortned',
    sa.Column('id', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('original_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('short_url', mysql.VARCHAR(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('short_url', 'shortned', ['short_url'], unique=False)
    op.create_table('shorturl',
    sa.Column('id', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('original_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('short_url', mysql.VARCHAR(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('async_test')
    # ### end Alembic commands ###
