"""new table

Revision ID: 72d8e2b5b92d
Revises: 72f4347c0d17
Create Date: 2022-08-02 15:14:28.925394

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '72d8e2b5b92d'
down_revision = '72f4347c0d17'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_srt',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('original_url', sa.String(length=255), nullable=True),
    sa.Column('code', sa.String(length=7), nullable=True),
    sa.Column('short_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.drop_index('code', table_name='async_test')
    op.drop_table('async_test')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('async_test',
    sa.Column('id', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('original_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('short_url', mysql.VARCHAR(length=7), nullable=True),
    sa.Column('code', mysql.VARCHAR(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('code', 'async_test', ['code'], unique=False)
    op.drop_table('url_srt')
    # ### end Alembic commands ###
