"""adding code

Revision ID: 72f4347c0d17
Revises: 706f57e034ce
Create Date: 2022-08-02 15:03:55.377216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72f4347c0d17'
down_revision = '706f57e034ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('async_test', sa.Column('code', sa.String(length=7), nullable=True))
    op.drop_index('short_url', table_name='async_test')
    op.create_unique_constraint(None, 'async_test', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'async_test', type_='unique')
    op.create_index('short_url', 'async_test', ['short_url'], unique=False)
    op.drop_column('async_test', 'code')
    # ### end Alembic commands ###
